// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5ywEU2lM3QHLeNGClqqFR-9aBp2WqXLs',
    appId: '1:966272867595:web:f0f79691ea03acc743d60e',
    messagingSenderId: '966272867595',
    projectId: 'gymui-25554',
    authDomain: 'gymui-25554.firebaseapp.com',
    storageBucket: 'gymui-25554.firebasestorage.app',
    measurementId: 'G-YMVW55S50P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXcqS4pUOoZHcEuycARtz49VrwEZ-0kWA',
    appId: '1:966272867595:android:4cf1c3cf8d5d503043d60e',
    messagingSenderId: '966272867595',
    projectId: 'gymui-25554',
    storageBucket: 'gymui-25554.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdWgSN6QkhGaXg886GDelf0LdkXLqKqoM',
    appId: '1:966272867595:ios:226626d0212acbfa43d60e',
    messagingSenderId: '966272867595',
    projectId: 'gymui-25554',
    storageBucket: 'gymui-25554.firebasestorage.app',
    iosBundleId: 'com.example.hymns',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdWgSN6QkhGaXg886GDelf0LdkXLqKqoM',
    appId: '1:966272867595:ios:226626d0212acbfa43d60e',
    messagingSenderId: '966272867595',
    projectId: 'gymui-25554',
    storageBucket: 'gymui-25554.firebasestorage.app',
    iosBundleId: 'com.example.hymns',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5ywEU2lM3QHLeNGClqqFR-9aBp2WqXLs',
    appId: '1:966272867595:web:873c4960d3366cb443d60e',
    messagingSenderId: '966272867595',
    projectId: 'gymui-25554',
    authDomain: 'gymui-25554.firebaseapp.com',
    storageBucket: 'gymui-25554.firebasestorage.app',
    measurementId: 'G-CBW4VWMC7B',
  );
}
